# Revising numpy from basic


In [4]:
import numpy as np

### creating a array from list



In [6]:
arr1= np.array([1,2,3,4,5])
print(arr1)
arr2= np.array([[1,2,3],[4,5,6]])
print(arr2)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]


### list vs numpy array

In [7]:
py_list=[1,2,3]
arr= np.array([1,2,3])
print(f"mulptiple list by 2: {py_list * 2}")
print(f"mulptiple array by 2: {arr * 2}")

mulptiple list by 2: [1, 2, 3, 1, 2, 3]
mulptiple array by 2: [2 4 6]


here we can the clear difference of in the output of multiplication 

In [8]:
import time 
start = time.time()
py_list = [i *2 for i in range(1000000)]
print(f"Time taken to multiply list: {time.time() - start} seconds")
start = time.time()
arr = np.arange(1000000) * 2
print(f"Time taken to multiply array: {time.time() - start} seconds")

Time taken to multiply list: 0.034509897232055664 seconds
Time taken to multiply array: 0.001512765884399414 seconds


the time diferrence is insane array is much much fatser than list


### creating array from scratch

In [11]:
# zeros array
arr_zeros = np.zeros((3, 4))
arr_zeros


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
np_ones = np.ones((3, 4))
print(f"Array of zeros:\n{arr_zeros}")

Array of zeros:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
