# Revising numpy from basic


In [2]:
import numpy as np

### creating a array from list



In [3]:
arr1= np.array([1,2,3,4,5])
print(arr1)
arr2= np.array([[1,2,3],[4,5,6]])
print(arr2)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]


### list vs numpy array

In [4]:
py_list=[1,2,3]
arr= np.array([1,2,3])
print(f"mulptiple list by 2: {py_list * 2}")
print(f"mulptiple array by 2: {arr * 2}")

mulptiple list by 2: [1, 2, 3, 1, 2, 3]
mulptiple array by 2: [2 4 6]


here we can the clear difference of in the output of multiplication 

In [5]:
import time 
start = time.time()
py_list = [i *2 for i in range(1000000)]
print(f"Time taken to multiply list: {time.time() - start} seconds")
start = time.time()
arr = np.arange(1000000) * 2
print(f"Time taken to multiply array: {time.time() - start} seconds")

Time taken to multiply list: 0.020924091339111328 seconds
Time taken to multiply array: 0.0021209716796875 seconds


the time diferrence is insane array is much much fatser than list


### creating array from scratch

In [6]:
# zeros array
arr_zeros = np.zeros((3, 4))
arr_zeros


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [7]:
np_ones = np.ones((3, 4))
print(f"Array of zeros:\n{arr_zeros}")

Array of zeros:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [10]:
np_full = np.full((3,4), 7)
np_full

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

In [11]:
np_random = np.random.random((3,4))
np_random


array([[0.48178841, 0.89757375, 0.43334883, 0.91485401],
       [0.97577948, 0.97156219, 0.4706321 , 0.04127439],
       [0.1937152 , 0.70688808, 0.38119584, 0.2691534 ]])

In [12]:
np_sequence = np.arange(10, 30, 5)
np_sequence

array([10, 15, 20, 25])

# vector , matrices, tensor


In [14]:
np_vector = np.array([1, 2, 3, 4, 5])
np_vector

array([1, 2, 3, 4, 5])

In [15]:
np_matrices = np.array([[1, 2, 3], [4, 5, 6]])
np_matrices

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
np_tensor = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(f"3D Tensor:\n{np_tensor}")

3D Tensor:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


# Array properties

In [20]:
arr=np.array([[1, 2, 3], [4, 5, 6]])
print(f" shape: {arr.shape}")
print(f" dimension: {arr.ndim}")
print(f" size: {arr.size}")
print(f" data type: {arr.dtype}")

 shape: (2, 3)
 dimension: 2
 size: 6
 data type: int64


# Array reshaping

In [28]:
arr= np.arange(12)
print(f"orignal array :{arr}")
arr_reshaped =arr.reshape((3, 4))
print(f"reshaped array :\n{arr_reshaped}")
flattend = arr_reshaped.flatten()
print(f"flattened array :\n{flattend}")


# ravel return view instead of copy
raveled = arr_reshaped.ravel()
print(f"raveled array :\n{raveled}")

# Transpose of an array
transposed = arr_reshaped.T
print(f"transposed array :\n{transposed}")

orignal array :[ 0  1  2  3  4  5  6  7  8  9 10 11]
reshaped array :
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
flattened array :
[ 0  1  2  3  4  5  6  7  8  9 10 11]
raveled array :
[ 0  1  2  3  4  5  6  7  8  9 10 11]
transposed array :
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
