In [1]:
import numpy as np


# Array operations

In [5]:
arr= np.arange(1,11)
print(arr)
# slicing
print(f"basic slicing :{arr[2:7]}")
print(f"step slicing :{arr[1:8:2]}")
print(f"negative slicing: {arr[2:-1]}")

[ 1  2  3  4  5  6  7  8  9 10]
basic slicing :[3 4 5 6 7]
step slicing :[2 4 6 8]
negative slicing: [3 4 5 6 7 8 9]


In [15]:
arr= np.arange(1,10).reshape(3,3)
print(arr)
print("getting a specific element",arr[1,2])
print("getting entire row :",arr[1])
print("getting entire column :",arr[:,1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
getting a specific element 6
getting entire row : [4 5 6]
getting entire column : [2 5 8]


### sorting

In [17]:
arr= np.array([1,5,3,2,8,9,4,0])
print("sorted array :",np.sort(arr))

arr_2d_unsorted = np.array([[1,5,3],[2,8,9],[4,0,6]])
print("sorted array along columns:\n", np.sort(arr_2d_unsorted, axis=0))
print("sorted array along rows:\n", np.sort(arr_2d_unsorted, axis=1))

sorted array : [0 1 2 3 4 5 8 9]
sorted array along columns:
 [[1 0 3]
 [2 5 6]
 [4 8 9]]
sorted array along rows:
 [[1 3 5]
 [2 8 9]
 [0 4 6]]


### filtering

In [19]:
arr= np.arange(1,11)
even= arr[arr%2==0]
print("even numbers from array:", even)

even numbers from array: [ 2  4  6  8 10]


## filter with mask

In [21]:
mask= arr>5
print("mask for elements greater than 5:", arr[mask])

mask for elements greater than 5: [ 6  7  8  9 10]


## fancy indexing and np.where()

In [25]:
idx=[2,4,8]
arr[idx]

where_result = np.where(arr>5)
print("np where",arr[where_result])

np where [ 6  7  8  9 10]


In [30]:
condition_arr = np.where(arr>5, 0, arr)
print("np where with condition:", condition_arr)

np where with condition: [1 2 3 4 5 0 0 0 0 0]


### adding and removing data

In [35]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])

combined_arr =np.concatenate((arr1, arr2))
print("combined array",combined_arr )

combined array [1 2 3 4 5 6]


### array compatiblity

In [37]:

a=np.array([1,2,3])
b=np.array([4,5,6])
c=np.array([7,8,9])

print("compatibility shape check:",a.shape==b.shape==c.shape)

compatibility shape check: True


In [42]:
orginal= np.array([[1,2,3],[4,5,6],[7,8,9]])
new_row = np.array([10,11,12])
new_arr = np.vstack((orginal, new_row))
print("new array after adding row:\n", new_arr)
new_col = np.array([[12],[12],[13]])
new_arr = np.hstack((orginal, new_col))
print("new array after adding column:\n", new_arr)

new array after adding row:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
new array after adding column:
 [[ 1  2  3 12]
 [ 4  5  6 12]
 [ 7  8  9 13]]


### deleting

In [43]:
arr=np.array([1,2,3,4,5])
deleted_arr = np.delete(arr, 2)  # delete element at index 2
print("array after deletion:", deleted_arr)

array after deletion: [1 2 4 5]
